name: Publish
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install --no-dev
    - name: Generate
      run: |
        poetry run python festivus.py
    - name: Publish
      run: |
        git config --global user.email "alex@pdp7.net"
        git config --global user.name "GitHub Actions"
        cd generated
        sudo chown -R $(id -un) .
        mv ../.git .
        git branch -M gh-pages
        git add -f .
        git commit -m 'Deploy'
        git push --force origin HEAD
